import type { Metadata } from "next";
import "./globals.css";
import vazirmatn from "@/utils/fonts";
import Providers from "@/providers/providers";
export const metadata: Metadata = {
  title: "کتابستان",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={` ${vazirmatn.className} antialiased bg-gray-100`}
      >
        <Providers >
            {children}
        </Providers>
      </body>
    </html>
  );
}
